inherit_gem:
  rubocop-github:
    - config/default_edge.yml
    - config/rails_edge.yml

AllCops:
  NewCops: enable
  Exclude:
    - "test/tmp/**/*"
    - "**/vendor/**/*"
    - "**/node_modules/**/*"

Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    - "stories/**/*"
    - "test/**/*"

Style/Documentation:
  Enabled: true
  Exclude:
    - "stories/**/*"
    - "test/**/*"
