name: Docs Build

on:
  push:
    branches:
      - master
      - st-statuses-action

jobs:
  build-docs:
    name: Update statuses project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-build-docs-${{ hashFiles('**/Gemfile.lock') }}
      - name: Rewrite code
        run: script/update-statuses-project.rb
